source 'https://rubygems.org'
gem 'jwt'
gem 'aws-sdk-core'
gem 'aws-sdk-secretsmanager'
gem 'rexml'
gem 'faraday'

gem 'sinatra', '>= 3.0'
gem 'secure_headers', '~> 6.5'
gem 'apigatewayv2_rack'
gem 'omniauth', '>= 2'
gem 'omniauth-himari'
gem 'rack-session'

gem 'rack', '~> 2.0' # FIXME: Upgrade to v3

group :development do
  gem 'puma'
end
